---
#set up the head node in the cluster
- name: Setup head node
  hosts: headNodes
  gather_facts: no
  remote_user: nvidia
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: make sure sshd settings are correct.
      template: src=/home/teamcrayowulf/head-config-files-temp/head/sshd_config dest=/etc/ssh

    - name: make sure iptables rules are in place
      template: src=/home/teamcrayowulf/head-config-files-temp/head/iptables.rules dest=/etc/iptables.rules

    - name: make sure iptables load script is in place.
      template: src=/home/teamcrayowulf/head-config-files-temp/head/iptablesload dest=/etc/network/if-pre-up.d/iptablesload

    - name: make sure iptables save script is in place.
      template: src=/home/teamcrayowulf/head-config-files-temp/head/iptablessave dest=/etc/network/if-post-down.d/iptablessave
    
    - name: Update package lists (equivalent to apt-get update)
      apt:
        update_cache: yes

    - name: Install available upgrades (equivalent to apt-get dist-upgrade)
      apt:
        upgrade: dist

    -name: Install misc necessary packages
     apt: 
        name: dhcp 
        state: installed

    - name: Assign IP addresses to interfaces
      template: src=/home/teamcrayowulf/head-config-files-temp/head/interfaces dest=/etc/network/interfaces

    - name: Enable IP Masquerading
      template: src=/home/teamcrayowulf/head-config-files-temp/head/rc.local dest=/etc/rc.local

    - name: put jetson in high performance mode
      command: nvpmodel -m 0
