---
#set up the head node in the cluster
- name: Setup head node
  hosts: headNode
  gather_facts: no
  remote_user: nvidia
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: make sure sshd settings are correct.
      template: src=/home/nvidia/files/head/sshd_config dest=/etc/ssh

    - name: make sure iptables rules are in place
      template: src=/home/nvidia/files/head/iptables.rules dest=/etc/iptables.rules

    - name: make sure iptables load script is in place.
      template: src=/home/nvidia/files/head/iptablesload dest=/etc/network/if-pre-up.d/iptablesload

    - name: make sure iptables save script is in place.
      template: src=/home/nvidia/files/head/iptablessave dest=/etc/network/if-post-down.d/iptablessave

    - name: put jetson in high performance mode
      command: nvpmodel -m 0
    
    - name: Update package lists (equivalent to apt-get update)
      apt:
        update_cache: yes

    - name: Install available upgrades (equivalent to apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Assign IP addresses to interfaces
      template: src=/home/nvidia/files/head/interfaces dest=/etc/network/interfaces

    - name: Install misc necessary packages
      apt: 
        name: isc-dhcp-server 
        state: installed

    - name: Place dhcpd.conf.  This file assigns ip addrs.
      template: src=/home/nvidia/files/head/dhcpd.conf dest=/etc/dhcp/dhcpd.conf

    - name: Place isc-dhcp-server.  This file tells isc-dhcp-server to only listen on eth1.
            # prevents you from running a dhcp server on your campus network.
      template: src=/home/nvidia/files/head/isc-dhcp-server dest=/etc/default/isc-dhcp-server

    - name: Enable IP Masquerading
      template: src=/home/nvidia/files/head/rc.local dest=/etc/rc.local


