---
#set up the worker nodes in the cluster
- name: Setup MPI on Worker Nodes
  hosts: "{{ on_hosts }}"
  gather_facts: no
  remote_user: nvidia
  become: yes
  become_method: sudo
  become_user: root

  tasks:
#If re-running the playbook due to one of the install tasks failing, these uninstall
#tasks will need to be commented out or otherwise disabled.

    -name: Purge all openmpi packages
     command: apt purge openmpi* libopenmpi*

#begin install tasks
    - name: Ensure custom openmpi-common is installed
      apt:
        deb: /home2/shared_install_files/openmpi/openmpi-common_1.10.104_all.deb

    - name: hold openmpi-common
      command: apt-mark hold openmpi-common

    - name: Ensure custom openmpi-doc is installed
      apt:
        deb: /home2/shared_install_files/openmpi/openmpi-doc_1.10.104_all.deb

    - name: hold openmpi-doc
      command: apt-mark hold openmpi-doc

    - name: Ensure custom libopenmpi1.10 is installed
      apt:
        deb: /home2/shared_install_files/openmpi/libopenmpi1.10_1.10.104_arm64.deb

    - name: hold libopenmpi1.10
      command: apt-mark hold libopenmpi1.10

    - name: Ensure custom openmpi-bin is installed
      apt:
        deb: /home2/shared_install_files/openmpi/openmpi-bin_1.10.104_arm64.deb

    - name: hold openmpi-bin
      command: apt-mark hold openmpi-bin

    - name: Ensure custom libopenmpi-dev is installed
      apt:
        deb: /home2/shared_install_files/openmpi/libopenmpi-dev_1.10.104_arm64.deb

    - name: hold libopenmpi-dev
      command: apt-mark hold libopenmpi-dev

    - name: Place /etc/openmpi/openmpi-mca-params.conf  (Open MPI settings)
      template: src=/home/nvidia/files/common/openmpi-mca-params.conf dest=/etc/openmpi/openmpi-mca-params.conf

    - name: Place /etc/openmpi/openmpi-default-hostfile  (Hosts available for Open MPI jobs)
      template: src=/home/nvidia/files/common/openmpi-default-hostfile dest=/etc/openmpi/openmpi-default-hostfile

    - name: Ensure libopenblas-dev is installed (Prerequisite for CUDA-Enabled HPL Benchmark)
      apt:
        name: libopenblas-dev
        state: installed

# end copied time zone setup steps
