---
- name: Setup for building VMD  www.ks.uiuc.edu/Research/vmd/
  hosts: headNode
  gather_facts: no
  remote_user: nvidia
  become: yes
  become_method: sudo
  become_user: root

  tasks:
#If re-running the playbook due to one of the install tasks failing, these uninstall
#tasks will need to be commented out or otherwise disabled.

#Uninstall tcl8.6

    - name: Ensure tcl8.6  is NOT installed
      apt:
        name: tcl8.6
        state: absent

    - name: Ensure tcl8.6-dev  is NOT installed
      apt:
        name: tcl8.6-dev
        state: absent

    - name: Ensure libtcl8.6  is NOT installed
      apt:
        name: libtcl8.6
        state: absent

#Install tcl8.5

    - name: Ensure tcl8.5  is installed
      apt:
        name: tcl8.5
        state: present

    - name: Ensure tcl8.5-dev  is installed
      apt:
        name: tcl8.5-dev
        state: present

    - name: Ensure libtcl8.5  is installed
      apt:
        name: libtcl8.5
        state: present

#Install tk8.5

    - name: Ensure tk8.5-dev  is installed
      apt:
        name: tk8.5-dev
        state: present

# Install FLTK

    - name: Ensure libfltk1.1-dev  is installed
      apt:
        name: libfltk1.1-dev
        state: present

    - name: Ensure libfltk1.1  is installed
      apt:
        name: libfltk1.1
        state: present

#Install other dependencies

    - name: Ensure libnetcdf-dev is installed
      apt:
        name: libnetcdf-dev
        state: present

    - name: Ensure libtachyon-dev-common is installed
      apt:
        name: libtachyon-dev-common
        state: present

    - name: Ensure tachyon-bin-ogl is installed
      apt:
        name: tachyon-bin-ogl
        state: present
