---
#set up the worker nodes in the cluster
- name: Setup worker nods
  hosts: workerNodes
  gather_facts: no
  remote_user: nvidia
  become: yes
  become_method: sudo
  become_user: root

  tasks:
   
    - name: disable wifi
      command: nmcli radio wifi off

    - name: put jetson in high performance mode
      command: nvpmodel -m 0

    - name: Place /etc/apt/sources.list (Enables universe repo)
      template: src=/home/nvidia/files/worker/sources.list dest=/etc/apt/sources.list
    
    - name: Update package lists (equivalent to apt-get update)
      apt:
        update_cache: yes

    - name: Install available upgrades (equivalent to apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Ensure rpcbind is installed (needed for NIS)
      apt:
        name: rpcbind
        state: installed

    - name: Ensure NIS is installed
      apt:
        name: nis
        state: installed

    - name: Place /etc/nsswitch.conf
      template: src=/home/nvidia/files/worker/nsswitch.conf dest=/etc/nsswitch.conf

    - name: Place /etc/rc.local
      template: src=/home/nvidia/files/worker/rc.local dest=/etc/rc.local

    - name: Place /etc/yp.conf
      template: src=/home/nvidia/files/common/yp.conf dest=/etc/yp.conf

    - name: Place /etc/timezone
      template: src=/home/nvidia/files/common/timezone dest=/etc/timezone

    - name: Ensure ntp is installed
      apt:
        name: ntp
        state: installed

#The following time zone setup steps copied from:
#https://getsatisfaction.cumulusnetworks.com/cumulus/topics/ansible-switch-basics-time-zone-and-ntp
# BJK Feb 13, 2018
    - name: Update tzdata with new time zone information
      command: dpkg-reconfigure -f noninteractive tzdata

    - name: Restart NTP service
      service: name=ntp state=restarted

# end copied time zone setup steps
