---
#set up the worker nodes in the cluster
- name: Setup worker nods
  hosts: workerNodes
  gather_facts: no
  remote_user: nvidia
  become: yes
  become_method: sudo
  become_user: root

  tasks:

    - name: disable wifi
      command: nmcli radio wifi off

    - name: make sure sshd settings are correct.
      template: src=/home/nvidia/files/worker/sshd_config dest=/etc/ssh/sshd_config

    - name: Place /etc/apt/sources.list (Enables universe repo)
      template: src=/home/nvidia/files/worker/sources.list dest=/etc/apt/sources.list

    - name: Ensure iptables-persistent is installed
      apt:
        name: iptables-persistent
        state: installed

    - name: make sure iptables rules are in place
      template: src=/home/nvidia/files/worker/iptables.rules dest=/etc/iptables/rules.v4

    - name: put jetson in high performance mode
      command: nvpmodel -m 0

    - name: Create /home2
      file:
        path: /home2
        state: directory
        mode: "u=rwx,g=rx,o=rx"

     #set hostname
    - hostname:
        name: "{{custom_hostname}}"


#    - name: Update package lists (equivalent to apt-get update)
#      apt:
#        update_cache: yes

#    - name: Install available upgrades (equivalent to apt-get dist-upgrade)
#      apt:
#        upgrade: dist

    - name: Place hosts file.  This file is used to mount the NFS share at boot time, before dns is available(?)
      template: src=/home/nvidia/files/worker/hosts dest=/etc/hosts

    - name: Ensure rpcbind is installed (needed for NIS)
      apt:
        name: rpcbind
        state: installed

    - name: Ensure NIS is installed
      apt:
        name: nis
        state: installed

    - name: Place /etc/nsswitch.conf
      template: src=/home/nvidia/files/worker/nsswitch.conf dest=/etc/nsswitch.conf

    - name: Place /etc/rc.local
      template: src=/home/nvidia/files/worker/rc.local dest=/etc/rc.local

    - name: Place /etc/yp.conf
      template: src=/home/nvidia/files/common/yp.conf dest=/etc/yp.conf

    - name: set timezone to America/Detroit
      timezone:
        name: America/Detroit

    - name: Ensure ntp is installed
      apt:
        name: ntp
        state: installed

    - name: Place /etc/ntp.conf
      template: src=/home/nvidia/files/worker/ntp.conf dest=/etc/ntp.conf

    - name: Restart NTP service
      service: name=ntp state=restarted

    - name: Ensure nfs-common is installed (needed to mount NFS shares)
      apt:
        name: nfs-common
        state: installed

    - name: Place /etc/fstab
      template: src=/home/nvidia/files/worker/fstab dest=/etc/fstab

    - name: Ensure rsh-redone-client is installed
      apt:
        name: rsh-redone-client
        state: installed

    - name: Ensure rsh-redone-server is installed
      apt:
        name: rsh-redone-server
        state: installed

    - name: Place /home/nvidia/.rhosts
      template: src=/home/nvidia/files/common/.rhosts dest=/home/nvidia/.rhosts owner=nvidia group=nvidia

    - name: Ensure libopenblas-dev is installed (Prerequisite for CUDA-Enabled HPL Benchmark)
      apt:
        name: libopenblas-dev
        state: installed

    # - name: Ensure openmpi-bin  is not installed
    #   apt:
    #     name: openmpi-bin
    #     state: absent
    #
    # - name: Ensure libopenmpi1.10  is not installed
    #   apt:
    #     name: libopenmpi1.10
    #     state: absent
    #
    # - name: Ensure libopenmpi-dev  is not installed
    #   apt:
    #     name: libopenmpi-dev
    #     state: absent

#Note: you may have to edit the links to the .deb files if their hosting location
#changes in the future.


    - name: Ensure custom openmpi-common is installed
      apt:
        deb: https://github.com/crayowulf/files/raw/master/common/openmpi-common_1.10.2-8ubuntu1_all.deb

    - name: hold openmpi-common
      command: apt-mark hold openmpi-common

    - name: Ensure custom openmpi-doc is installed
      apt:
        deb: https://github.com/crayowulf/files/raw/master/common/openmpi-doc_1.10.2-8ubuntu1_all.deb

    - name: hold openmpi-doc
      command: apt-mark hold openmpi-doc

    - name: Ensure custom libopenmpi-dev is installed
      apt:
        deb: https://github.com/crayowulf/files/raw/master/common/libopenmpi-dev_1.10.2-8ubuntu1_arm64.deb

    - name: hold libopenmpi-dev
      command: apt-mark hold libopenmpi-dev

    - name: Ensure custom libopenmpi1.10 is installed
      apt:
        deb: https://github.com/crayowulf/files/raw/master/common/libopenmpi1.10_1.10.2-8ubuntu1_arm64.deb

    - name: hold libopenmpi1.10
      command: apt-mark hold libopenmpi1.10

    #place custom openmpi-bin installer
    - synchronize:
         src: /home/nvidia/files/common/openmpi-bin_1.10.2-8ubuntu1_arm64.deb
         dest: /home/nvidia/openmpi-bin_1.10.2-8ubuntu1_arm64.deb

    - name: install openmpi-bin
      command: dpkg -i -B --force-depends  /home/nvidia/openmpi-bin_1.10.2-8ubuntu1_arm64.deb

    - name: hold openmpi-bin
      command: apt-mark hold openmpi-bin


    - name: Place /etc/openmpi/openmpi-mca-params.conf  (Open MPI settings)
      template: src=/home/nvidia/files/common/openmpi-mca-params.conf dest=/etc/openmpi/openmpi-mca-params.conf

    - name: Place /etc/openmpi/openmpi-default-hostfile  (Hosts available for Open MPI jobs)
      template: src=/home/nvidia/files/common/openmpi-default-hostfile dest=/etc/openmpi/openmpi-default-hostfile

# end copied time zone setup steps
