---
#set up the worker nodes in the cluster
- name: Setup worker nods
  hosts: workerNodes
  gather_facts: no
  remote_user: nvidia
  become: yes
  become_method: sudo
  become_user: root

  tasks:
   
    - name: disable wifi
      command: nmcli radio wifi off

    - name: put jetson in high performance mode
      command: nvpmodel -m 0

     #set hostname
    - hostname:
        name: "{{custom_hostname}}"

    - name: Place /etc/apt/sources.list (Enables universe repo)
      template: src=/home/nvidia/files/worker/sources.list dest=/etc/apt/sources.list
    
    - name: Update package lists (equivalent to apt-get update)
      apt:
        update_cache: yes

    - name: Install available upgrades (equivalent to apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Ensure rpcbind is installed (needed for NIS)
      apt:
        name: rpcbind
        state: installed

    - name: Ensure NIS is installed
      apt:
        name: nis
        state: installed

    - name: Place /etc/nsswitch.conf
      template: src=/home/nvidia/files/worker/nsswitch.conf dest=/etc/nsswitch.conf

    - name: Place /etc/rc.local
      template: src=/home/nvidia/files/worker/rc.local dest=/etc/rc.local

    - name: Place /etc/yp.conf
      template: src=/home/nvidia/files/common/yp.conf dest=/etc/yp.conf

    - name: set timezone to America/Detroit
      timezone:
        name: America/Detroit

    - name: Ensure ntp is installed
      apt:
        name: ntp
        state: installed

    - name: Place /etc/ntp.conf
      template: src=/home/nvidia/files/worker/ntp.conf dest=/etc/ntp.conf

    - name: Restart NTP service
      service: name=ntp state=restarted

    - name: Ensure nfs-common is installed (needed to mount NFS shares)
      apt:
        name: nfs-common
        state: installed

    - name: Ensure /media/cluster_files directory exists, create if not.
      file:
        path: /media/cluster_files
        state: directory
        mode: 0777

    - name: Place /etc/fstab
      template: src=/home/nvidia/files/worker/fstab dest=/etc/fstab

# end copied time zone setup steps
